language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev

script:
  - cp config/settings.ini.default config/settings.ini
  - cd guzzle-active-record-sample
  - ../vendor/bin/phpunit
